preprocessing:
  min_sales_threshold: 10


feature_engineering:
  loess_frac: 0.3
  seasonality_method: dummy  # Options: dummy, stl, spline


mixed_modeling:
  lvl1: brand
  lvl2: sub_brand
  lvl3: ppg_id
  lvl4: retailer_id
  fe_lvl1_var: ['log_avg_price', 'log_promo_acv_tpr']
  fe_lvl2_var: ['log_avg_price', 'log_promo_acv_tpr']
  fe_lvl3_var: ['log_avg_price', 'log_promo_acv_tpr', 'trend', 'holiday_flag', 'log_cpi']
  fe_lvl4_var: ['log_avg_price', 'log_promo_acv_tpr', 'trend', 'holiday_flag', 'log_cpi']
  re_lvl1_var: []
  re_lvl2_var: []
  re_lvl3_var: []
  re_lvl4_var: []